apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-service-v1
spec:
  selector:
    matchLabels:
      app: rest-service-v1
  template:
    metadata:
      labels:
        app: rest-service-v1
    spec:
      containers:
        - name: rest-service-v1
          image: rest-service
          env:
            - name: version
              value: "V1"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: http
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /hello
              port: http
            initialDelaySeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: rest-service-v1
spec:
  ports:
    - port: 8080
      targetPort: 3000
  selector:
    app: rest-service-v1
  type: ClusterIP
