apiVersion: apps/v1
kind: Deployment
metadata:
  name: soap-service-v2
spec:
  selector:
    matchLabels:
      app: soap-service-v2
  template:
    metadata:
      labels:
        app: soap-service-v2
    spec:
      containers:
        - name: soap-service-v2
          image: soap-service
          env:
            - name: version
              value: "V2"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /ws/countries.wsdl
              port: http
            initialDelaySeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: soap-service-v2
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: soap-service-v2
  type: ClusterIP
